### ISSUE TITLE
[Bug] 双显示器 Windows 版 v1.5/v.5.1 每次启动后, 主界面都会向右下方发生移动

### ISSUE THREAD

**Issue by foobarjohnny** [LibNyanpasu/clash-nyanpasu#558] opened 2024-03-05 08:59 UTC
### 复现步骤 / Step to reproduce

1. 双显示器的 Windows 10 系统 (必须是双显示器, 单显示器无法复现)
2. 启动 clash-nyanpasu
3. 退出
4. 再启动 clash-nyanpasu 

### 预期行为 / Expected behaviour

主界面应该显示在上次退出时的位置.

### 实际行为 / Actual Behaviour

主界面却显示在了上次退出时位置的右下方一些儿.

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.0

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 10

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment] 2024-03-05 12:53
@4o3F Please have a check. Thank you.

**Comment by 4o3F** [comment] 2024-03-05 13:08
Can't reproduce, would you please provide a screen recording?

**Comment by utopeadia** [comment] 2024-03-06 02:23
same problem

**Comment by utopeadia** [comment] 2024-03-06 02:25
I use the horizontal screen on the left (24 inch 2K resolution) and the vertical screen on the right (the same display, rotating 90 degrees). The probability of recurrence is almost 100%. When the main interface is opened, it appears on the right edge of the vertical screen, and the main interface can only leak half or all is hidden.

**Comment by 4o3F** [comment] 2024-03-06 02:30
Will this happen when you close app on either screen? Or just when it's closed on the vertical screen

**Comment by utopeadia** [comment] 2024-03-06 02:52
> Will this happen when you close app on either screen? Or just when it's closed on the vertical screen

i will give u a vedio

Uploading 1709693465832-video_20240306_104858.mp4…

**Comment by utopeadia** [comment] 2024-03-06 02:52
https://github.com/LibNyanpasu/clash-nyanpasu/assets/98788152/67846ec4-969d-4407-899b-e060ce9953b9

**Comment by foobarjohnny** [comment] 2024-03-06 05:10
> Can't reproduce, would you please provide a screen recording?

由于是在旧电脑上添加新的大显示器, 新旧显示器对 DVI, DisplayPort 接口支持的原因, 所以不得已把 DVI 上的小显示器设置为第2显示器, 把 DisplayPort 上的 4K 屏大显示器设置为第1显示器. 你可以试试把你的 1, 2 显示器在 Windows 配置中调换一下, 看看能不能复现.

**Comment by 4o3F** [comment] 2024-03-06 14:16
Fixed in 072d03086ff42a40b71651394bf38d099ecb032c

**Closed by 4o3F** 2024-03-06 14:16 UTC
Labels: T: Bug, S: Untriaged
